Reduced number of sentences as the current 5 is too much data causing a fatal error.
--
yomateod@DESKTOP-SR72DSK:/mnt/c/workspace/ui/express-graphql-typescript-boilerplate$ npm run db:seed

> express-graphql-typescript-boilerplate@1.0.0-rc.3 db:seed /mnt/c/workspace/ui/express-graphql-typescript-boilerplate
> knex seed:run

Requiring external module ts-node/register
Using environment: development
Error: ER_DATA_TOO_LONG: Data too long for column 'description' at row 8